name: redux_persist_flutter
description: Redux Persist Flutter Integration with custom storage engines
version: 0.8.2
homepage: https://github.com/Cretezy/redux_persist/tree/master/packages/redux_persist_flutter
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: "flutter"
  path_provider: "^1.2.0"
  shared_preferences: "^0.5.3"
  redux_persist:
    url: git://github.com/RubisetCie/redux_persist
    path: ../redux_persist
